
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: forum_development

test:
  <<: *default
  database: forum_test

production:
  <<: *default
  database: forum_production
  username: forum
  password: <%= ENV['FORUM_DATABASE_PASSWORD'] %>

